'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50215.44
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.ComponentModel.ToolboxItem(true),  _
 System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 System.Xml.Serialization.XmlRootAttribute("TestDataSet"),  _
 System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet"),  _
 System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly")>  _
Partial Public Class TestDataSet
    Inherits System.Data.DataSet
    
    Private tableAnimals As AnimalsDataTable
    
    Private _schemaSerializationMode As System.Data.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema
    
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")>  _
    Protected Sub New(ByVal info As System.Runtime.Serialization.SerializationInfo, ByVal context As System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As System.Data.DataSet = New System.Data.DataSet
            ds.ReadXmlSchema(New System.Xml.XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("Animals")) Is Nothing) Then
                MyBase.Tables.Add(New AnimalsDataTable(ds.Tables("Animals")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New System.Xml.XmlTextReader(New System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property Animals() As AnimalsDataTable
        Get
            Return Me.tableAnimals
        End Get
    End Property
    
    Public Overrides Property SchemaSerializationMode() As System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <System.ComponentModel.DefaultValueAttribute(true)>  _
    Public Shadows Property EnforceConstraints() As Boolean
        Get
            Return MyBase.EnforceConstraints
        End Get
        Set
            MyBase.EnforceConstraints = value
        End Set
    End Property
    
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    Public Overrides Function Clone() As System.Data.DataSet
        Dim cln As TestDataSet = CType(MyBase.Clone,TestDataSet)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As System.Data.DataSet = New System.Data.DataSet
            ds.ReadXml(reader)
            If (Not (ds.Tables("Animals")) Is Nothing) Then
                MyBase.Tables.Add(New AnimalsDataTable(ds.Tables("Animals")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tableAnimals = CType(MyBase.Tables("Animals"),AnimalsDataTable)
        If (initTable = true) Then
            If (Not (Me.tableAnimals) Is Nothing) Then
                Me.tableAnimals.InitVars
            End If
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "TestDataSet"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/TestDataSet.xsd"
        Me.EnforceConstraints = true
        Me.tableAnimals = New AnimalsDataTable
        MyBase.Tables.Add(Me.tableAnimals)
    End Sub
    
    Private Function ShouldSerializeAnimals() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Shared Function GetTypedDataSetSchema(ByVal xs As System.Xml.Schema.XmlSchemaSet) As System.Xml.Schema.XmlSchemaComplexType
        Dim ds As TestDataSet = New TestDataSet
        Dim type As System.Xml.Schema.XmlSchemaComplexType = New System.Xml.Schema.XmlSchemaComplexType
        Dim sequence As System.Xml.Schema.XmlSchemaSequence = New System.Xml.Schema.XmlSchemaSequence
        xs.Add(ds.GetSchemaSerializable)
        Dim any As System.Xml.Schema.XmlSchemaAny = New System.Xml.Schema.XmlSchemaAny
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Return type
    End Function
    
    Public Delegate Sub AnimalsRowChangeEventHandler(ByVal sender As Object, ByVal e As AnimalsRowChangeEvent)
    
    <System.Serializable(),  _
     System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class AnimalsDataTable
        Inherits System.Data.DataTable
        Implements System.Collections.IEnumerable
        
        Private columnAnimalID As System.Data.DataColumn
        
        Private columnAnimalName As System.Data.DataColumn
        
        Public Sub New()
            MyBase.New
            Me.TableName = "Animals"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        Friend Sub New(ByVal table As System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        Protected Sub New(ByVal info As System.Runtime.Serialization.SerializationInfo, ByVal context As System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        Public ReadOnly Property AnimalIDColumn() As System.Data.DataColumn
            Get
                Return Me.columnAnimalID
            End Get
        End Property
        
        Public ReadOnly Property AnimalNameColumn() As System.Data.DataColumn
            Get
                Return Me.columnAnimalName
            End Get
        End Property
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As AnimalsRow
            Get
                Return CType(Me.Rows(index),AnimalsRow)
            End Get
        End Property
        
        Public Event AnimalsRowChanged As AnimalsRowChangeEventHandler
        
        Public Event AnimalsRowChanging As AnimalsRowChangeEventHandler
        
        Public Event AnimalsRowDeleted As AnimalsRowChangeEventHandler
        
        Public Event AnimalsRowDeleting As AnimalsRowChangeEventHandler
        
        Public Overloads Sub AddAnimalsRow(ByVal row As AnimalsRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddAnimalsRow(ByVal AnimalID As Integer, ByVal AnimalName As String) As AnimalsRow
            Dim rowAnimalsRow As AnimalsRow = CType(Me.NewRow,AnimalsRow)
            rowAnimalsRow.ItemArray = New Object() {AnimalID, AnimalName}
            Me.Rows.Add(rowAnimalsRow)
            Return rowAnimalsRow
        End Function
        
        Public Function FindByAnimalID(ByVal AnimalID As Integer) As AnimalsRow
            Return CType(Me.Rows.Find(New Object() {AnimalID}),AnimalsRow)
        End Function
        
        Public Overridable Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As System.Data.DataTable
            Dim cln As AnimalsDataTable = CType(MyBase.Clone,AnimalsDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As System.Data.DataTable
            Return New AnimalsDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnAnimalID = MyBase.Columns("AnimalID")
            Me.columnAnimalName = MyBase.Columns("AnimalName")
        End Sub
        
        Private Sub InitClass()
            Me.columnAnimalID = New System.Data.DataColumn("AnimalID", GetType(Integer), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnAnimalID)
            Me.columnAnimalName = New System.Data.DataColumn("AnimalName", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnAnimalName)
            Me.Constraints.Add(New System.Data.UniqueConstraint("Constraint1", New System.Data.DataColumn() {Me.columnAnimalID}, true))
            Me.columnAnimalID.AllowDBNull = false
            Me.columnAnimalID.Unique = true
            Me.columnAnimalName.AllowDBNull = false
            Me.columnAnimalName.MaxLength = 50
        End Sub
        
        Public Function NewAnimalsRow() As AnimalsRow
            Return CType(Me.NewRow,AnimalsRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As System.Data.DataRowBuilder) As System.Data.DataRow
            Return New AnimalsRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(AnimalsRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.AnimalsRowChangedEvent) Is Nothing) Then
                RaiseEvent AnimalsRowChanged(Me, New AnimalsRowChangeEvent(CType(e.Row,AnimalsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.AnimalsRowChangingEvent) Is Nothing) Then
                RaiseEvent AnimalsRowChanging(Me, New AnimalsRowChangeEvent(CType(e.Row,AnimalsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.AnimalsRowDeletedEvent) Is Nothing) Then
                RaiseEvent AnimalsRowDeleted(Me, New AnimalsRowChangeEvent(CType(e.Row,AnimalsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.AnimalsRowDeletingEvent) Is Nothing) Then
                RaiseEvent AnimalsRowDeleting(Me, New AnimalsRowChangeEvent(CType(e.Row,AnimalsRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveAnimalsRow(ByVal row As AnimalsRow)
            Me.Rows.Remove(row)
        End Sub
        
        Public Shared Function GetTypedTableSchema(ByVal xs As System.Xml.Schema.XmlSchemaSet) As System.Xml.Schema.XmlSchemaComplexType
            Dim type As System.Xml.Schema.XmlSchemaComplexType = New System.Xml.Schema.XmlSchemaComplexType
            Dim sequence As System.Xml.Schema.XmlSchemaSequence = New System.Xml.Schema.XmlSchemaSequence
            Dim ds As TestDataSet = New TestDataSet
            xs.Add(ds.GetSchemaSerializable)
            Dim any1 As System.Xml.Schema.XmlSchemaAny = New System.Xml.Schema.XmlSchemaAny
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As System.Xml.Schema.XmlSchemaAny = New System.Xml.Schema.XmlSchemaAny
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As System.Xml.Schema.XmlSchemaAttribute = New System.Xml.Schema.XmlSchemaAttribute
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As System.Xml.Schema.XmlSchemaAttribute = New System.Xml.Schema.XmlSchemaAttribute
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "AnimalsDataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Return type
        End Function
    End Class
    
    Partial Public Class AnimalsRow
        Inherits System.Data.DataRow
        
        Private tableAnimals As AnimalsDataTable
        
        Friend Sub New(ByVal rb As System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tableAnimals = CType(Me.Table,AnimalsDataTable)
        End Sub
        
        Public Property AnimalID() As Integer
            Get
                Return CType(Me(Me.tableAnimals.AnimalIDColumn),Integer)
            End Get
            Set
                Me(Me.tableAnimals.AnimalIDColumn) = value
            End Set
        End Property
        
        Public Property AnimalName() As String
            Get
                Return CType(Me(Me.tableAnimals.AnimalNameColumn),String)
            End Get
            Set
                Me(Me.tableAnimals.AnimalNameColumn) = value
            End Set
        End Property
    End Class
    
    Public Class AnimalsRowChangeEvent
        Inherits System.EventArgs
        
        Private eventRow As AnimalsRow
        
        Private eventAction As System.Data.DataRowAction
        
        Public Sub New(ByVal row As AnimalsRow, ByVal action As System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row() As AnimalsRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action() As System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class

Namespace TestDataSetTableAdapters
    
    <System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.ComponentModel.ToolboxItem(true),  _
     System.ComponentModel.DataObjectAttribute(true),  _
     System.ComponentModel.DesignerAttribute("Microsoft.VSDesigner.DataSource.Design.TableAdapterDesigner, Microsoft.VSDesigner"& _ 
        ", Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"),  _
     System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")>  _
    Partial Public Class AnimalsTableAdapter
        Inherits System.ComponentModel.Component
        
        Private WithEvents m_adapter As System.Data.SqlClient.SqlDataAdapter
        
        Private m_connection As System.Data.SqlClient.SqlConnection
        
        Private m_commandCollection() As System.Data.SqlClient.SqlCommand
        
        Private m_clearBeforeFill As Boolean
        
        Public Sub New()
            MyBase.New
            Me.m_clearBeforeFill = true
        End Sub
        
        Private ReadOnly Property Adapter() As System.Data.SqlClient.SqlDataAdapter
            Get
                If (Me.m_adapter Is Nothing) Then
                    Me.InitAdapter
                End If
                Return Me.m_adapter
            End Get
        End Property
        
        Friend Property Connection() As System.Data.SqlClient.SqlConnection
            Get
                If (Me.m_connection Is Nothing) Then
                    Me.InitConnection
                End If
                Return Me.m_connection
            End Get
            Set
                Me.m_connection = value
                If (Not (Me.Adapter.InsertCommand) Is Nothing) Then
                    Me.Adapter.InsertCommand.Connection = value
                End If
                If (Not (Me.Adapter.DeleteCommand) Is Nothing) Then
                    Me.Adapter.DeleteCommand.Connection = value
                End If
                If (Not (Me.Adapter.UpdateCommand) Is Nothing) Then
                    Me.Adapter.UpdateCommand.Connection = value
                End If
                Dim i As Integer = 0
                Do While (i < Me.CommandCollection.Length)
                    If (Not (Me.CommandCollection(i)) Is Nothing) Then
                        CType(Me.CommandCollection(i),System.Data.SqlClient.SqlCommand).Connection = value
                    End If
                    i = (i + 1)
                Loop
            End Set
        End Property
        
        Protected ReadOnly Property CommandCollection() As System.Data.SqlClient.SqlCommand()
            Get
                If (Me.m_commandCollection Is Nothing) Then
                    Me.InitCommandCollection
                End If
                Return Me.m_commandCollection
            End Get
        End Property
        
        Public Property ClearBeforeFill() As Boolean
            Get
                Return Me.m_clearBeforeFill
            End Get
            Set
                Me.m_clearBeforeFill = value
            End Set
        End Property
        
        Private Sub InitAdapter()
            Me.m_adapter = New System.Data.SqlClient.SqlDataAdapter
            Dim tableMapping As System.Data.Common.DataTableMapping = New System.Data.Common.DataTableMapping
            tableMapping.SourceTable = "Table"
            tableMapping.DataSetTable = "Animals"
            tableMapping.ColumnMappings.Add("AnimalID", "AnimalID")
            tableMapping.ColumnMappings.Add("AnimalName", "AnimalName")
            Me.m_adapter.TableMappings.Add(tableMapping)
            Me.m_adapter.DeleteCommand = New System.Data.SqlClient.SqlCommand
            Me.m_adapter.DeleteCommand.Connection = Me.Connection
            Me.m_adapter.DeleteCommand.CommandText = "DELETE FROM [dbo].[Animals] WHERE (([AnimalID] = @Original_AnimalID) AND ([Animal"& _ 
                "Name] = @Original_AnimalName))"
            Me.m_adapter.DeleteCommand.CommandType = System.Data.CommandType.Text
            Me.m_adapter.DeleteCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Original_AnimalID", System.Data.SqlDbType.Int, 0, System.Data.ParameterDirection.Input, 0, 0, "AnimalID", System.Data.DataRowVersion.Original, false, Nothing, "", "", ""))
            Me.m_adapter.DeleteCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Original_AnimalName", System.Data.SqlDbType.VarChar, 0, System.Data.ParameterDirection.Input, 0, 0, "AnimalName", System.Data.DataRowVersion.Original, false, Nothing, "", "", ""))
            Me.m_adapter.InsertCommand = New System.Data.SqlClient.SqlCommand
            Me.m_adapter.InsertCommand.Connection = Me.Connection
            Me.m_adapter.InsertCommand.CommandText = "INSERT INTO [dbo].[Animals] ([AnimalID], [AnimalName]) VALUES (@AnimalID, @Animal"& _ 
                "Name);"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"SELECT AnimalID, AnimalName FROM Animals WHERE (AnimalID = @AnimalID)"
            Me.m_adapter.InsertCommand.CommandType = System.Data.CommandType.Text
            Me.m_adapter.InsertCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@AnimalID", System.Data.SqlDbType.Int, 0, System.Data.ParameterDirection.Input, 0, 0, "AnimalID", System.Data.DataRowVersion.Current, false, Nothing, "", "", ""))
            Me.m_adapter.InsertCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@AnimalName", System.Data.SqlDbType.VarChar, 0, System.Data.ParameterDirection.Input, 0, 0, "AnimalName", System.Data.DataRowVersion.Current, false, Nothing, "", "", ""))
            Me.m_adapter.UpdateCommand = New System.Data.SqlClient.SqlCommand
            Me.m_adapter.UpdateCommand.Connection = Me.Connection
            Me.m_adapter.UpdateCommand.CommandText = "UPDATE [dbo].[Animals] SET [AnimalID] = @AnimalID, [AnimalName] = @AnimalName WHE"& _ 
                "RE (([AnimalID] = @Original_AnimalID) AND ([AnimalName] = @Original_AnimalName))"& _ 
                ";"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"SELECT AnimalID, AnimalName FROM Animals WHERE (AnimalID = @AnimalID)"
            Me.m_adapter.UpdateCommand.CommandType = System.Data.CommandType.Text
            Me.m_adapter.UpdateCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@AnimalID", System.Data.SqlDbType.Int, 0, System.Data.ParameterDirection.Input, 0, 0, "AnimalID", System.Data.DataRowVersion.Current, false, Nothing, "", "", ""))
            Me.m_adapter.UpdateCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@AnimalName", System.Data.SqlDbType.VarChar, 0, System.Data.ParameterDirection.Input, 0, 0, "AnimalName", System.Data.DataRowVersion.Current, false, Nothing, "", "", ""))
            Me.m_adapter.UpdateCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Original_AnimalID", System.Data.SqlDbType.Int, 0, System.Data.ParameterDirection.Input, 0, 0, "AnimalID", System.Data.DataRowVersion.Original, false, Nothing, "", "", ""))
            Me.m_adapter.UpdateCommand.Parameters.Add(New System.Data.SqlClient.SqlParameter("@Original_AnimalName", System.Data.SqlDbType.VarChar, 0, System.Data.ParameterDirection.Input, 0, 0, "AnimalName", System.Data.DataRowVersion.Original, false, Nothing, "", "", ""))
        End Sub
        
        Private Sub InitConnection()
            Me.m_connection = New System.Data.SqlClient.SqlConnection
            Me.m_connection.ConnectionString = Exercise_9_1.Settings.Default.TestConnectionString
        End Sub
        
        Private Sub InitCommandCollection()
            Me.m_commandCollection = New System.Data.SqlClient.SqlCommand(0) {}
            Me.m_commandCollection(0) = New System.Data.SqlClient.SqlCommand
            Me.m_commandCollection(0).Connection = Me.Connection
            Me.m_commandCollection(0).CommandText = "SELECT AnimalID, AnimalName FROM dbo.Animals"
            Me.m_commandCollection(0).CommandType = System.Data.CommandType.Text
        End Sub
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Fill, true)>  _
        Public Overloads Overridable Function Fill(ByVal dataTable As TestDataSet.AnimalsDataTable) As Integer
            Me.Adapter.SelectCommand = Me.CommandCollection(0)
            If (Me.m_clearBeforeFill = true) Then
                dataTable.Clear
            End If
            Dim returnValue As Integer = Me.Adapter.Fill(dataTable)
            Return returnValue
        End Function
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.[Select], true)>  _
        Public Overloads Overridable Function GetData() As TestDataSet.AnimalsDataTable
            Me.Adapter.SelectCommand = Me.CommandCollection(0)
            Dim dataTable As TestDataSet.AnimalsDataTable = New TestDataSet.AnimalsDataTable
            Me.Adapter.Fill(dataTable)
            Return dataTable
        End Function
        
        Public Overloads Overridable Function Update(ByVal dataTable As TestDataSet.AnimalsDataTable) As Integer
            Return Me.Adapter.Update(dataTable)
        End Function
        
        Public Overloads Overridable Function Update(ByVal dataSet As TestDataSet) As Integer
            Return Me.Adapter.Update(dataSet, "Animals")
        End Function
        
        Public Overloads Overridable Function Update(ByVal dataRow As System.Data.DataRow) As Integer
            Return Me.Adapter.Update(New System.Data.DataRow() {dataRow})
        End Function
        
        Public Overloads Overridable Function Update(ByVal dataRows() As System.Data.DataRow) As Integer
            Return Me.Adapter.Update(dataRows)
        End Function
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Delete, true)>  _
        Public Overloads Overridable Function Delete(ByVal Original_AnimalID As Integer, ByVal Original_AnimalName As String) As Integer
            Me.Adapter.DeleteCommand.Parameters(0).Value = CType(Original_AnimalID,Integer)
            If (Original_AnimalName Is Nothing) Then
                Throw New System.ArgumentNullException("Original_AnimalName")
            Else
                Me.Adapter.DeleteCommand.Parameters(1).Value = CType(Original_AnimalName,String)
            End If
            Dim previousConnectionState As System.Data.ConnectionState = Me.Adapter.DeleteCommand.Connection.State
            Me.Adapter.DeleteCommand.Connection.Open
            Try 
                Return Me.Adapter.DeleteCommand.ExecuteNonQuery
            Finally
                If (previousConnectionState = System.Data.ConnectionState.Closed) Then
                    Me.Adapter.DeleteCommand.Connection.Close
                End If
            End Try
        End Function
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Insert, true)>  _
        Public Overloads Overridable Function Insert(ByVal AnimalID As Integer, ByVal AnimalName As String) As Integer
            Me.Adapter.InsertCommand.Parameters(0).Value = CType(AnimalID,Integer)
            If (AnimalName Is Nothing) Then
                Throw New System.ArgumentNullException("AnimalName")
            Else
                Me.Adapter.InsertCommand.Parameters(1).Value = CType(AnimalName,String)
            End If
            Dim previousConnectionState As System.Data.ConnectionState = Me.Adapter.InsertCommand.Connection.State
            Me.Adapter.InsertCommand.Connection.Open
            Try 
                Return Me.Adapter.InsertCommand.ExecuteNonQuery
            Finally
                If (previousConnectionState = System.Data.ConnectionState.Closed) Then
                    Me.Adapter.InsertCommand.Connection.Close
                End If
            End Try
        End Function
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Update, true)>  _
        Public Overloads Overridable Function Update(ByVal AnimalID As Integer, ByVal AnimalName As String, ByVal Original_AnimalID As Integer, ByVal Original_AnimalName As String) As Integer
            Me.Adapter.UpdateCommand.Parameters(0).Value = CType(AnimalID,Integer)
            If (AnimalName Is Nothing) Then
                Throw New System.ArgumentNullException("AnimalName")
            Else
                Me.Adapter.UpdateCommand.Parameters(1).Value = CType(AnimalName,String)
            End If
            Me.Adapter.UpdateCommand.Parameters(2).Value = CType(Original_AnimalID,Integer)
            If (Original_AnimalName Is Nothing) Then
                Throw New System.ArgumentNullException("Original_AnimalName")
            Else
                Me.Adapter.UpdateCommand.Parameters(3).Value = CType(Original_AnimalName,String)
            End If
            Dim previousConnectionState As System.Data.ConnectionState = Me.Adapter.UpdateCommand.Connection.State
            Me.Adapter.UpdateCommand.Connection.Open
            Try 
                Return Me.Adapter.UpdateCommand.ExecuteNonQuery
            Finally
                If (previousConnectionState = System.Data.ConnectionState.Closed) Then
                    Me.Adapter.UpdateCommand.Connection.Close
                End If
            End Try
        End Function
    End Class
End Namespace
